INSERT INTO USER_DTLS(ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED)
 VALUES(1, 'pisharma', 'password', 'Piyush', 'Sharma', 'Y');

INSERT INTO AUTHORITY_DTLS(USER_ID, AUTHORITY)
VALUES(1, 'Admin');