CREATE TABLE AUTH.SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME NUMBER(19,0) NOT NULL,
	LAST_ACCESS_TIME NUMBER(19,0) NOT NULL,
	MAX_INACTIVE_INTERVAL NUMBER(10,0) NOT NULL,
	EXPIRY_TIME NUMBER(19,0) NOT NULL,
	PRINCIPAL_NAME VARCHAR2(100 CHAR),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) TABLESPACE AUTH_TABLESPACE;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON AUTH.SPRING_SESSION (SESSION_ID)
tablespace AUTH_TABLESPACE;
CREATE INDEX SPRING_SESSION_IX2 ON AUTH.SPRING_SESSION (EXPIRY_TIME)
tablespace AUTH_TABLESPACE;
CREATE INDEX SPRING_SESSION_IX3 ON AUTH.SPRING_SESSION (PRINCIPAL_NAME)
tablespace AUTH_TABLESPACE;

CREATE TABLE AUTH.SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR2(200 CHAR) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES AUTH.SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
)tablespace AUTH_TABLESPACE;