INSERT INTO USER_DTLS(ID, USERNAME, FIRSTNAME, LASTNAME, USERTYPE,
EMAIL, ADDRESS, PHONE)
 VALUES(1, 'pisharma', 'Piyush', 'Sharma', 'EMPLOYEE', 'pisharma@gmail.com',
 '239 Gurgaon', '8860765478');

INSERT INTO USER_DTLS(ID, USERNAME, FIRSTNAME, LASTNAME, USERTYPE,
EMAIL, ADDRESS, PHONE)
 VALUES(2, 'ajkumar', 'Ajay', 'Kumar', 'AFFILIATE', 'ajkumar@gmail.com',
 '239 Bangalore', '8860765479');

INSERT INTO USER_DTLS(ID, USERNAME, FIRSTNAME, LASTNAME, USERTYPE,
EMAIL, ADDRESS, PHONE)
 VALUES(3, 'anilkumar', 'Anil', 'Kumar', 'CUSTOMER', 'anilkumar@gmail.com',
 '239 Chennai', '8860765477');


 INSERT INTO PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, UNITS_AVAILABLE,
 DESCRIPTION, PRICE)
  VALUES(1, 'GRC001', 'COCA-COLA', 'GROCERY', '100', 'SOFT_DRINK',
  4);

  INSERT INTO PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, UNITS_AVAILABLE,
   DESCRIPTION, PRICE)
    VALUES(2, 'CL001', 'POLO_SHIRT', 'CLOTHING', '100', 'CLOTHING',
    5);

  INSERT INTO PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, UNITS_AVAILABLE,
     DESCRIPTION, PRICE)
      VALUES(3, 'FR001', 'SOFA', 'FURNITURE', '100', 'FURNITURE',
      25);

  INSERT INTO PRODUCT(ID, PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, UNITS_AVAILABLE,
       DESCRIPTION, PRICE)
        VALUES(4, 'SEC001', 'CAMERA', 'SECURITY_SUPPLIES', '100', 'SECURITY_SUPPLIES',
        25);